### ISSUE TITLE
Desenvolvedores não conseguem controlar custos de Cloud

### ISSUE THREAD

**Issue by hugocostazup** [stack-spot/stackspot-roadmap#174]
## The Pain

Para desenvolvedores de software, a falta de clareza sobre os custos de cloud é um desafio significativo. A complexidade dos modelos de preços e a variabilidade das cobranças associadas aos serviços de cloud podem tornar extremamente difícil para os desenvolvedores estimar e controlar os custos dos projetos.

Os desenvolvedores frequentemente enfrentam dificuldades para entender como suas escolhas de serviços e configurações impactam os custos gerais. Com modelos de preços que variam com base no uso, tipo de serviço e opções de configuração, prever os custos exatos torna-se uma tarefa complicada. Isso pode resultar em surpresas financeiras indesejadas, quando os gastos reais se mostram muito superiores ao orçamento inicialmente planejado.

Além disso, a falta de transparência detalhada sobre quais serviços estão consumindo mais recursos e como esses custos se acumulam ao longo do tempo pode complicar ainda mais a gestão financeira dos projetos. Sem visibilidade clara sobre o consumo, os desenvolvedores podem encontrar dificuldades em justificar os gastos e em alocar recursos de forma eficiente, afetando a capacidade de tomar decisões técnicas e financeiras informadas.

## Summary

Para desenvolvedores de software, a falta de clareza sobre os custos de cloud representa um dos principais desafios na adoção e gestão de serviços de cloud. A dificuldade em entender e prever os custos devido à complexidade dos modelos de preços e à variabilidade dos gastos pode levar a surpresas financeiras e problemas no planejamento orçamentário dos projetos.

Para enfrentar esse desafio, é crucial que os desenvolvedores adotem ferramentas e práticas de gestão de custos que ofereçam visibilidade e transparência detalhadas sobre o consumo e os gastos com serviços de cloud. Implementar soluções eficazes de monitoramento e controle financeiro pode ajudar a manter os custos sob controle, otimizar o uso dos recursos e permitir uma tomada de decisão mais estratégica e informada.

## Goal

Proporcionar uma visão clara dos gastos com cloud e oferecer as ferramentas e o conhecimento necessários para gerenciar e otimizar esses custos de forma proativa e eficaz, atendendo às necessidades específicas dos desenvolvedores e das equipes de engenharia.

## Possible Features

- **Visão geral de custos**: Disponibilizamos dashboards interativos que mostram o consumo detalhado dos principais serviços de cloud em tempo real. Esses dashboards permitem que os desenvolvedores vejam exatamente onde os recursos estão sendo consumidos e como isso impacta os custos.
- **Forecast**: Utilizando algoritmos de machine learning e análise preditiva, é possível antecipar as necessidades de recursos com base em padrões históricos de uso e projeções de crescimento. Essas previsões permitem um planejamento financeiro mais preciso, ajudando as empresas a identificar oportunidades de economia e a planejar investimentos futuros. 
- **Saving Plans**: [todo]
- **Right Sizing**: Análise contínua do desempenho e uso dos recursos, ajustando as alocações para evitar o provisionamento excessivo ou insuficiente. Ferramentas de análise de performance identificam oportunidades para otimizar o uso dos recursos, recomendando ajustes que podem reduzir custos sem comprometer a performance.
- **Relatórios:** Proveremos relatórios detalhados e customizáveis que mostram a distribuição dos custos por equipe, projeto ou serviço, facilitando a atribuição de gastos e a justificativa de despesas.

## Frequency

Alta: De acordo com o relatório "2023 State of the Cloud Report" da Flexera, 72% dos respondentes têm time de FinOps e 14% planejam criar nos próximos 12 meses. ([link para apresentação](https://docs.google.com/presentation/d/1y4eik6mZmKf4GrKmBzliwnQ712E2oKwr/edit#slide=id.p7))

## Coverage

Alta: 82% das empresas relataram que gerir gastos de nuvem é prioridade dos respondentes, superando Cloud Security pela primeira vez na década. E apenas 57% delas usam ferramentas de FinOps.

**Comment by edwardmonteiro** [comment]
Fala com alguma dor declarada em algum cliente ? Exemplo Itau ? Qual a dor e qual persona será usuario da proposta de valor ?

**Comment by edwardmonteiro** [comment]
Outro ponto aqui parece que fomos mais na oportunidade do mercado, do que de fato na dor existente no cliente, além disso usar um relatório como parte do processo de decisão me parece ser algo que ajuda a calibrar, porém não é algo determinante para definir se devemos ou nao construir algo.

**Comment by edwardmonteiro** [comment]
alem disso nao sei se a dor é do engenheiro de software ou do tech lead , gestor do custo ? voces inestigaram isso ?

**Comment by fernandesZup** [comment]
Olá @edwardmonteiro boa tarde, mais uma vez obrigado pelo feedback. 

Iremos ajustar o texto para dar uma maior clareza do foco de dor além do ajuste do título do Épico. 

Estágio deste Epic: em design 
A princípio temos duas personas envolvidas no processo: tech lead e gestor do custo 

voces inestigaram isso ?
Houveram diversos alinhamentos e conversas com time de finOps Itaú olhando para uma perspectiva desta persona 'gestor do custo'
A fase atual do design estamos validando a dor com tech leads e desenvolvedores.

**Comment by cadupereira-zup** [comment]
@fernandesZup complementando o comentário do @edwardmonteiro, reforço a necessidade de destacarmos casos observáveis e evidências nas dores. Você consegue descrever esta dor exatamente igual com o cenário atual de gestão de custos da StackSpot e possivelmente com cenários semelhantes no banco. Quando trazemos desenvolvedores de forma ampla deixamos aberto este tipo de questionamento.
