### ISSUE TITLE
Tempo elevado para criar e expor uma API

### ISSUE THREAD

**Issue by gsmjaoy** [stack-spot/stackspot-roadmap#179]
## The Pain
Usuários leva um tempo elevado para criar e expor uma API

## Summary
Atualmente existem várias etapas ao longo da jornada de criação e publicação de APIs, sendo que nem todas etapas estão automatizadas. Alem disso, as etapas de provisionamento de infraestrutura, aplicação, contrato/documentação não estão muito integradas, o que eleva o nível de complexidade para o usuário.

## Goal
Reduzir o tempo total para disponizar a primeira versão de uma API com um template inicial em desenvolvimento (Outer Loop)

## **Possible Features**
- Setup inicial unico para criar uma nova API
- Preenchimento automatica de informações que hoje são manuais
- Geração automatica dos templates/artefatos necessários para a pessoa desenvolvedora codar 

## **Metrics**
- Leadtime da jornada 
- Nível de satisfação dos usuários (CSAT)

## **Frequency**
Ocorre quando usuários precisam criar novas APIs. Atualmente a media de novas APIs criadas é de 200/mês

## **Coverage**
Alta: Ocorre com todas as pessoas desenvolvedoras que precisam criar novas APIs.

**Comment by edwardmonteiro** [comment]
Qual tempo elevado ? e baseado em quais evidencias podemos afirmar isso ? A metrica principal seria otimizar o tempo de publicação e reduzir o esforço ? Caso positivo, será que medir o Customer Effort Score , nao ajudaria ?

Exemplos do CES

Customer Effort Score (CES). CES is an important metric that helps companies understand how easy or difficult it is for customers to interact with their products or services. Here are some sample questions you could use:

"On a scale of 1-7, how easy was it to resolve your issue today?"
(1 = Very Difficult, 7 = Very Easy)
"How much effort did you personally have to put forth to handle your request?"
(1 = Very Low Effort, 7 = Very High Effort)
"[Company Name] made it easy for me to handle my issue."
(Strongly Disagree 1 2 3 4 5 6 7 Strongly Agree)
"How easy was it to get the help you needed today?"
(Extremely Difficult 1 2 3 4 5 Extremely Easy)
"To what extent do you agree with the following statement: The company made it easy for me to solve my problem."
(Strongly Disagree 1 2 3 4 5 Strongly Agree)
"How easy was it to find the information you were looking for on our website?"
(Very Difficult 1 2 3 4 5 6 7 Very Easy)
"How would you rate the ease of your checkout process?"
(Extremely Difficult 1 2 3 4 5 Extremely Easy)

**Comment by cadupereira-zup** [comment]
@gilmareste complementando o comentário do @edwardmonteiro me parece que esta dor envolve diversas outras dores tratadas em outros cards, é quase uma composição de várias partes.
