### ISSUE TITLE
Usuário gostaria de realizar a jornada de consumo de uma API a partir do IDE

### ISSUE THREAD

**Issue by gsmjaoy** [stack-spot/stackspot-roadmap#181]

**Comment by edwardmonteiro** [comment]
Aqui é mais um desejo ou uma dor ?

**Comment by cadupereira-zup** [comment]
@gsmjaoy +1 parece mais uma hipótese do que uma dor.

**Comment by marceloamaralzup** [comment]
sugiro ponderar se é o anseio de uma pessoa. se for o caso, explorar melhor o motivo e, a partir de mais dados sobre esse desejo, entender se pode ganhar escala ou pode ser uma hipótese a ser testada com outras pessoas.
