### ISSUE TITLE
Falta de visibilidade e controle dos recursos em nuvem compromete a governança, gera desperdícios e limita o crescimento do negócio

### ISSUE THREAD

**Issue by fernandesZup** [stack-spot/stackspot-roadmap#219]
Need design 
## A dor
Gestores de TI e equipes de governança do Itaú perdem o controle sobre os recursos em múltiplas nuvens, resultando em gastos excessivos, riscos de segurança e ineficiência operacional.

## Contexto
O Itaú enfrenta um crescimento exponencial no uso de recursos em múltiplas nuvens públicas. A complexidade de gerenciar esses ambientes criou uma necessidade urgente de melhorar a visibilidade e o controle. A falta de uma solução unificada prejudica a conformidade, a otimização de custos e a maximização do valor dos investimentos em nuvem. A StackSpot está desenvolvendo uma fundação de cloud para abordar essas questões, inicialmente focada nos gestores de TI e equipes de governança.

## Evidências
- O Itaú gasta R$8M por ano com sua atual PaaS (RedHat OpenShift).
- Há uma meta de economia de R$8M/ano com PaaS entre 2025 e 2028.
- Existe um objetivo de gerar R$50M adicionais através de novos contratos em 2025.
- Infraestrutura atual:
  - 8,5 mil contas AWS
  - 3 milhões de funções Lambda
  - 700 clusters EKS
  - 9 mil clusters ECS
  - 5 mil instâncias RDS
- Apenas 134 pessoas na comunidade Cloud gerenciam toda essa infraestrutura.

## Frequência
Contínua. A falta de visibilidade e controle afeta diariamente todas as operações e decisões relacionadas aos recursos em nuvem.

## Impacto
Alto. Resulta em gastos excessivos, aumento nos riscos de segurança, não conformidade com regulações, ineficiência operacional generalizada e dificuldade em escalar operações de forma sustentável.

## Recorrência
Afeta toda a organização de TI do Itaú, incluindo gestores de TI, equipes de governança, engenheiros de plataforma, desenvolvedores, equipes de operações de TI, equipes de segurança e gestores financeiros.

## Objetivo
Implementar uma solução de fundação de cloud multicloud que proporcione visibilidade completa e em tempo real de todos os recursos em nuvem, controle centralizado e automatizado da infraestrutura, otimização contínua de custos e recursos, governança simplificada e capacidade de escalar operações de forma eficiente.

## Possíveis Funcionalidades
- Dashboard Multicloud Unificado: Interface centralizada para visualização e gerenciamento de recursos em múltiplos provedores de nuvem (inicialmente AWS e OCI).
- Sistema de Alertas Inteligentes: Notificações proativas para uso anômalo ou excessivo de recursos, potenciais riscos de segurança e questões de conformidade.
- GuardRails Automatizados: Implementação e aplicação automática de políticas de segurança e conformidade em todos os ambientes de nuvem.
- Gerenciamento Centralizado de Políticas: Ponto único de controle para criar, atualizar e aplicar políticas de segurança e conformidade em todas as plataformas de nuvem.

## Métricas de sucesso
- Redução de 30% nos custos gerais de nuvem até 2026.
- Aumento de 50% na velocidade de identificação e resolução de problemas de recursos.
- Obtenção de margem positiva em todos os clientes até dezembro de 2025.
- Aumento de 40% na eficiência operacional da equipe de Cloud.
- Atingir o objetivo de R$50M em novos contratos em 2025.

**Comment by marceloamaralzup** [comment]
As 134 pessoas que gerenciam são os CTOs e os gerentes ou são pessoas que fazem esse trabalho sob supervisão desses perfis? É importante considerar nesse mapeamento como cada ator se envolve nessa gestão e quais são as ferramentas que auxiliam nas tarefas que compreendem gerir. A dificuldade de gerir está em ferramental, processos ou em como as equipes estão estruturadas? Em casos como esse, é importante detalhar esse pontos para que a solução encontrada não seja sabotada pela forma que o trabalho é conduzido pelas pessoas no dia a dia.
